---
- hosts: loadbalancer
  gather_facts: false
  become: true
  tasks:
    - name: verify nginx service
      command: service nginx status

    - name: verify nginx is listening on port 80
      wait_for:
        port: 80
        timeout: 1

- hosts: webserver
  gather_facts: false
  become: true
  tasks:
    - name: verify apache2 service
      command: service apache2 status
      changed_when: false

    - name: verify apache2 is listening on port 80
      wait_for:
        port: 80
        timeout: 1
# - hosts: database
#   gather_facts: false
#   become: true
#   tasks:
#     - name: verify myql service
#       command: service mysql status
#       changed_when: false

#     - name: verify mysql is listening on port 3306
#       wait_for:
#         host: "{{ ansible_eth0.ipv4.address }}"
#         port: 3306
#         timeout: 1

# - hosts: control
#   tasks:
#     - name: verify end-to-end response
#       uri:
#         url: http://{{item}}
#         return_content: yes
#         with_items: groups.loadbalancer
#         register: lb_index

#     - fail:
#         msg: "index failed to return content"
#       when: "'hello' not in item.content"
#       with_items: "{{lb_index.results}}"

